# typed: false
# frozen_string_literal: true

# This file was generated by the Homebrew formula generator
class ScAgent < Formula
  desc "Aikido Security SC-Agent"
  homepage "https://github.com/tudor-timcu/sc-agent"
  version "1.7.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/AikidoSec/sc-agent/releases/download/v#{version}/sc-agent-darwin-amd64"
      sha256 "af90cfc15cd625f7cfe1e5900465d786ed1f2c84ae1b3bc9a24e90f88fb8ddc2"
    end
    if Hardware::CPU.arm?
      url "https://github.com/AikidoSec/sc-agent/releases/download/v#{version}/sc-agent-darwin-arm64"
      sha256 "8c021407db6029f4c50849ceab2c88bb70f24aa5aab85a6f6444b5c659a020de"
    end
  end

  def install
    binary_name = Hardware::CPU.intel? ? "sc-agent-darwin-amd64" : "sc-agent-darwin-arm64"
    
    # Try to find the file - Homebrew might have renamed it
    downloaded_file = if File.exist?(binary_name)
      binary_name
    elsif (file = Dir.glob("*").find { |f| File.file?(f) && File.executable?(f) })
      file
    else
      raise "Could not find downloaded binary file"
    end
    
    bin.install downloaded_file => "sc-agent"
    chmod 0755, bin/"sc-agent"
  end

  service do
    name macos: "com.aikidosecurity.sc-agent"
    run [opt_bin/"sc-agent"]
    run_at_load true
    keep_alive true
    require_root true
    log_path "/var/log/aikidosecurity/sc-agent.log"
    error_log_path "/var/log/aikidosecurity/sc-agent.error.log"
  end

  test do
    system "#{bin}/sc-agent", "--version"
  end
end

