# typed: false
# frozen_string_literal: true

# This file was generated by the Homebrew formula generator
class ScAgent < Formula
  desc "Safechain agent daemon"
  homepage "https://github.com/tudor-timcu/sc-agent"
  version "pr-1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/AikidoSec/sc-agent/releases/download/v1.4.0/sc-agent-darwin-amd64"
      sha256 "7b2d017e890ab6017e542750512507182b6bcb630ecbdf1eecd3a6defcfbc3cd"
    end
    if Hardware::CPU.arm?
      url "https://github.com/AikidoSec/sc-agent/releases/download/v1.4.0/sc-agent-darwin-arm64"
      sha256 "d26e640694917b890dcf6b74f45a09fa4d6828860e01c8c01b7c9cad3bfcc59f"
    end
  end

  def install
    binary_name = Hardware::CPU.intel? ? "sc-agent-darwin-amd64" : "sc-agent-darwin-arm64"
    
    # Try to find the file - Homebrew might have renamed it
    downloaded_file = if File.exist?(binary_name)
      binary_name
    elsif (file = Dir.glob("*").find { |f| File.file?(f) && File.executable?(f) })
      file
    else
      raise "Could not find downloaded binary file"
    end
    
    bin.install downloaded_file => "sc-agent"
    chmod 0755, bin/"sc-agent"
  end

  def post_install
    # Create plist file for launchd
    plist_path = "#{ENV['HOME']}/Library/LaunchAgents/com.aikidosecurity.sc-agent.plist"
    system "mkdir", "-p", File.dirname(plist_path)
    
    File.write(plist_path, plist_content)
    ohai "Created LaunchAgent plist at #{plist_path}"
    ohai "To start the daemon, run: launchctl load #{plist_path}"
    ohai "To stop the daemon, run: launchctl unload #{plist_path}"
  end

  def plist_content
    <<~PLIST
      <?xml version="1.0" encoding="UTF-8"?>
      <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
      <plist version="1.0">
      <dict>
        <key>Label</key>
        <string>com.aikidosecurity.sc-agent</string>
        <key>ProgramArguments</key>
        <array>
          <string>#{bin}/sc-agent</string>
        </array>
        <key>RunAtLoad</key>
        <true/>
        <key>KeepAlive</key>
        <true/>
        <key>StandardOutPath</key>
        <string>#{var}/log/sc-agent.log</string>
        <key>StandardErrorPath</key>
        <string>#{var}/log/sc-agent.error.log</string>
      </dict>
      </plist>
    PLIST
  end

  test do
    system "#{bin}/sc-agent", "--version"
  end
end

